<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <langVersion>latest</langVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
    <!-- Disables .exe.config generation and copy -->
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateApplicationConfigurationFile>false</GenerateApplicationConfigurationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http"/>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.46">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="8.0.5"/>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
    <PackageReference Include="YamlDotNet" Version="18.1.0"/>
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

  <Target Name="RemoveExeConfig" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Delete Files="$(TargetDir)$(TargetName).exe.config"/>
  </Target>
</Project>
